$(document).ready(function(){
  $('ul.destination-list').hide();
  $('.learnmore').click(function(){
    $(this).next('ul.destination-list').slideDown('fast').addClass('active');
    $('.close').click(function(){
      $(this).parent().slideUp('fast').removeClass('active');
    });
  });
});